import type { Track, Artist, User, Comment } from '@/types';

// ============================================================
// DADOS DE DEMONSTRAÇÃO
// Usados quando o Supabase não está configurado.
// ============================================================

export const DEMO_ARTISTS: Artist[] = [
  {
    id: 'artist-1',
    name: 'DJ Thunder',
    avatar_url: '/demo-artist-1.jpg',
    cover_url: '/demo-cover-1.jpg',
    bio: 'Eletrônica | Bass Music',
    genre: 'Eletrônica',
    followers_count: 12400,
  },
  {
    id: 'artist-2',
    name: 'Luna Vox',
    avatar_url: '/demo-artist-2.jpg',
    cover_url: '/demo-cover-2.jpg',
    bio: 'Indie | Dream Pop',
    genre: 'Indie',
    followers_count: 8900,
  },
  {
    id: 'artist-3',
    name: 'MC Flow',
    avatar_url: '/demo-artist-3.jpg',
    cover_url: '/demo-cover-3.jpg',
    bio: 'Hip Hop | Trap',
    genre: 'Hip Hop',
    followers_count: 23100,
  },
  {
    id: 'artist-4',
    name: 'Neon Pulse',
    avatar_url: '/demo-artist-4.jpg',
    cover_url: '/demo-cover-4.jpg',
    bio: 'Synthwave | Retro',
    genre: 'Synthwave',
    followers_count: 5600,
  },
  {
    id: 'artist-5',
    name: 'Sombra',
    avatar_url: '/demo-artist-5.jpg',
    cover_url: '/demo-cover-5.jpg',
    bio: 'R&B | Soul',
    genre: 'R&B',
    followers_count: 15200,
  },
  {
    id: 'artist-6',
    name: 'Banda Aurora',
    avatar_url: '/demo-artist-6.jpg',
    cover_url: '/demo-cover-6.jpg',
    bio: 'Rock Alternativo',
    genre: 'Rock',
    followers_count: 9800,
  },
  {
    id: 'artist-7',
    name: 'Kiko Beatz',
    avatar_url: '/demo-artist-7.jpg',
    cover_url: '/demo-cover-7.jpg',
    bio: 'Funk | Bass',
    genre: 'Funk',
    followers_count: 31200,
  },
  {
    id: 'artist-8',
    name: 'Velvet Skies',
    avatar_url: '/demo-artist-8.jpg',
    cover_url: '/demo-cover-8.jpg',
    bio: 'Lo-Fi | Chill',
    genre: 'Lo-Fi',
    followers_count: 18500,
  },
];

export const DEMO_TRACKS: Track[] = [
  {
    id: 'track-1',
    title: 'Bass Drop',
    artist_id: 'artist-1',
    artist_name: 'DJ Thunder',
    cover_url: '/demo-cover-1.jpg',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    duration: 215,
    plays_count: 45000,
    created_at: '2025-01-15T10:00:00Z',
  },
  {
    id: 'track-2',
    title: 'Lua Cheia',
    artist_id: 'artist-2',
    artist_name: 'Luna Vox',
    cover_url: '/demo-cover-2.jpg',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    duration: 198,
    plays_count: 32000,
    created_at: '2025-02-10T14:30:00Z',
  },
  {
    id: 'track-3',
    title: 'Fogo na Rua',
    artist_id: 'artist-3',
    artist_name: 'MC Flow',
    cover_url: '/demo-cover-3.jpg',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    duration: 175,
    plays_count: 67000,
    created_at: '2025-03-05T08:00:00Z',
  },
  {
    id: 'track-4',
    title: 'Neon Drive',
    artist_id: 'artist-4',
    artist_name: 'Neon Pulse',
    cover_url: '/demo-cover-4.jpg',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    duration: 243,
    plays_count: 21000,
    created_at: '2025-01-20T16:00:00Z',
  },
  {
    id: 'track-5',
    title: 'Noite Sem Fim',
    artist_id: 'artist-5',
    artist_name: 'Sombra',
    cover_url: '/demo-cover-5.jpg',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    duration: 220,
    plays_count: 28000,
    created_at: '2025-04-12T20:00:00Z',
  },
  {
    id: 'track-6',
    title: 'Revolução',
    artist_id: 'artist-6',
    artist_name: 'Banda Aurora',
    cover_url: '/demo-cover-6.jpg',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    duration: 265,
    plays_count: 19000,
    created_at: '2025-02-28T12:00:00Z',
  },
  {
    id: 'track-7',
    title: 'Vai no Beat',
    artist_id: 'artist-7',
    artist_name: 'Kiko Beatz',
    cover_url: '/demo-cover-7.jpg',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
    duration: 185,
    plays_count: 52000,
    created_at: '2025-05-01T22:00:00Z',
  },
  {
    id: 'track-8',
    title: 'Chill Vibes',
    artist_id: 'artist-8',
    artist_name: 'Velvet Skies',
    cover_url: '/demo-cover-8.jpg',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
    duration: 310,
    plays_count: 38000,
    created_at: '2025-03-15T06:00:00Z',
  },
  {
    id: 'track-9',
    title: 'Ritmo Total',
    artist_id: 'artist-1',
    artist_name: 'DJ Thunder',
    cover_url: '/demo-cover-1.jpg',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3',
    duration: 192,
    plays_count: 41000,
    created_at: '2025-04-20T18:00:00Z',
  },
  {
    id: 'track-10',
    title: 'Sonho Digital',
    artist_id: 'artist-4',
    artist_name: 'Neon Pulse',
    cover_url: '/demo-cover-4.jpg',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3',
    duration: 228,
    plays_count: 15000,
    created_at: '2025-05-10T15:00:00Z',
  },
  {
    id: 'track-11',
    title: 'Meu Mundo',
    artist_id: 'artist-2',
    artist_name: 'Luna Vox',
    cover_url: '/demo-cover-2.jpg',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3',
    duration: 205,
    plays_count: 25000,
    created_at: '2025-06-01T09:00:00Z',
  },
  {
    id: 'track-12',
    title: 'Grave Baixo',
    artist_id: 'artist-7',
    artist_name: 'Kiko Beatz',
    cover_url: '/demo-cover-7.jpg',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3',
    duration: 168,
    plays_count: 58000,
    created_at: '2025-06-15T23:00:00Z',
  },
];

export const DEMO_COMMENTS: Comment[] = [
  {
    id: 'comment-1',
    user_id: 'user-2',
    track_id: 'track-1',
    content: 'Essa batida é insana! 🔥',
    created_at: '2025-06-20T14:30:00Z',
    user: {
      id: 'user-2',
      email: 'maria@email.com',
      name: 'Maria Silva',
      avatar_url: null,
      created_at: '2025-01-01T00:00:00Z',
    },
  },
  {
    id: 'comment-2',
    user_id: 'user-3',
    track_id: 'track-1',
    content: 'Tô ouvindo em loop já',
    created_at: '2025-06-20T15:45:00Z',
    user: {
      id: 'user-3',
      email: 'pedro@email.com',
      name: 'Pedro Santos',
      avatar_url: null,
      created_at: '2025-01-05T00:00:00Z',
    },
  },
  {
    id: 'comment-3',
    user_id: 'user-2',
    track_id: 'track-3',
    content: 'MC Flow sempre entregando! 💪',
    created_at: '2025-06-21T10:00:00Z',
    user: {
      id: 'user-2',
      email: 'maria@email.com',
      name: 'Maria Silva',
      avatar_url: null,
      created_at: '2025-01-01T00:00:00Z',
    },
  },
];

export const DEMO_USER: User = {
  id: 'user-1',
  email: 'demo@zoada.com',
  name: 'Demo User',
  avatar_url: null,
  created_at: '2025-01-01T00:00:00Z',
};

// Color palette for generated cover art
export const COVER_COLORS = [
  ['#FF8C42', '#E84393'],
  ['#6C5CE7', '#00CEC9'],
  ['#E84393', '#6C5CE7'],
  ['#FDCB6E', '#FF8C42'],
  ['#00CEC9', '#6C5CE7'],
  ['#E84393', '#FF8C42'],
  ['#6C5CE7', '#E84393'],
  ['#FDCB6E', '#6C5CE7'],
];
